[workspace]
members = [
    "crates/shell",
    "crates/builtins/*",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "TODO"

[workspace.dependencies]
clap = { version = "4.5.20", features = ["derive"] }
